### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by 64600013** [hashinami46/sakamichi-app-ts-cli#2]
I believe I extracted the catalog correctly, and I name the file to the latest date(223090801 If I'm not wrong). 
Did I install incorrectly? 
Or I'm messing up the argument in token? If so, how do I determine the range index of the catalog?
```
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```

**Comment by 64600013** [comment]
I found the problem. On my second review of the problem, I found that for some reason my system installed an old release of node instead of the latest version. 
So I nuked everything and reinstalled it, and now it's working fine.

**Comment by hashinami46** [comment]
> I found the problem. On my second review of the problem, I found that for some reason my system installed an old release of node instead of the latest version. 
> So I nuked everything and reinstalled it, and now it's working fine.

Please update your nodejs
